#!/usr/bin/env bash
set -euo pipefail

RUN_ID="${AUTORAG_DEMO_RUN_ID:-m6}"
INPUT_DIR="${AUTORAG_DEMO_INPUT_DIR:-data/fixtures/pdfs}"
QUESTION="${AUTORAG_DEMO_QUESTION:-Compare mitigation and acceptance strategies.}"
MODE="${AUTORAG_DEMO_MODE:-hybrid}"
TOP_K="${AUTORAG_DEMO_TOP_K:-8}"
REPORTS_DIR="${AUTORAG_DEMO_REPORTS_DIR:-reports/milestones}"
MATRIX_REPORTS_DIR="${AUTORAG_DEMO_MATRIX_REPORTS_DIR:-reports/experiments}"
EMBEDDING_PROVIDER="${AUTORAG_EMBEDDING_PROVIDER:-local_hash}"
EMBEDDING_MODEL="${AUTORAG_EMBEDDING_MODEL:-bge-small-en-v1.5}"
RERANKER_ENABLED="${AUTORAG_RERANKER_ENABLED:-false}"
RERANKER_MODEL="${AUTORAG_RERANKER_MODEL:-llama3:8b}"
RERANKER_CANDIDATE_K="${AUTORAG_RERANKER_CANDIDATE_K:-30}"
OLLAMA_BASE_URL="${AUTORAG_OLLAMA_BASE_URL:-http://localhost:11434}"
OLLAMA_TIMEOUT_SECONDS="${AUTORAG_OLLAMA_TIMEOUT_SECONDS:-30}"

export AUTORAG_EMBEDDING_PROVIDER="${EMBEDDING_PROVIDER}"
export AUTORAG_EMBEDDING_MODEL="${EMBEDDING_MODEL}"
export AUTORAG_RERANKER_ENABLED="${RERANKER_ENABLED}"
export AUTORAG_RERANKER_MODEL="${RERANKER_MODEL}"
export AUTORAG_RERANKER_CANDIDATE_K="${RERANKER_CANDIDATE_K}"
export AUTORAG_OLLAMA_BASE_URL="${OLLAMA_BASE_URL}"
export AUTORAG_OLLAMA_TIMEOUT_SECONDS="${OLLAMA_TIMEOUT_SECONDS}"

uv run autorag demo-build \
  --run-id "${RUN_ID}" \
  --input "${INPUT_DIR}" \
  --question "${QUESTION}" \
  --mode "${MODE}" \
  --top-k "${TOP_K}" \
  --reports-dir "${REPORTS_DIR}" \
  --matrix-reports-dir "${MATRIX_REPORTS_DIR}"
